### ISSUE TITLE
Error al crear una cancha

### ISSUE THREAD

**Issue by earias08** [EzequielMassa/AlAnguloFrontend#78]
**Proceso**
Dar de alta una cancha en la página del administrador

**Resultado esperado**
visualizar los datos de la cancha correctamente

**Resultado actual**
Al completar el formulario de alta de una cancha el nombre solicita un maximo de 100 caracteres, la descripción un maximo de 500 caracteres, al ingresar esos valores, no se visualizan correctamente en la vista de todas las canchas. En cuanto a diseño el campo de la descripción deberia ser un textarea. 
Ademas agregar un tope maximo en el precio de las canchas, estas ya tienen un minimo, pero se puede agregar cualquier valor. 

**Captura**
![image](https://github.com/EzequielMassa/AlAnguloFrontend/assets/18445151/c75e1a83-b21c-444f-a075-d89a12c68a38)
![image](https://github.com/EzequielMassa/AlAnguloFrontend/assets/18445151/d6cd130d-b279-4a3d-994a-f18dc55d63df)
![image](https://github.com/EzequielMassa/AlAnguloFrontend/assets/18445151/80d019fa-0742-4956-ac6e-3f6a1f744559)

**Comment by EzequielMassa** [comment]
corregidos los issues mencionados

**Comment by earias08** [comment]
Al crear una cancha con un nombre largo ya se ve perfecto en la vista de la lista de canchas, pero no se ve correctamente en la vista de las reservas en dispositivos moviles

![image](https://github.com/EzequielMassa/AlAnguloFrontend/assets/18445151/a6b377da-067a-4e19-b0a6-4d59e91f4282)

**Comment by EzequielMassa** [comment]
> Al crear una cancha con un nombre largo ya se ve perfecto en la vista de la lista de canchas, pero no se ve correctamente en la vista de las reservas en dispositivos moviles
> 
> ![image](https://private-user-images.githubusercontent.com/18445151/331432887-a6b377da-067a-4e19-b0a6-4d59e91f4282.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzUyMjksIm5iZiI6MTcxNTk3NDkyOSwicGF0aCI6Ii8xODQ0NTE1MS8zMzE0MzI4ODctYTZiMzc3ZGEtMDY3YS00ZTE5LWIwYTYtNGQ1OWU5MWY0MjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE5NDIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYTFlNDAwOWU4YzBmNTIxNGFlM2E4Y2JmNDJiOWFiZjA2NTNkZWQ4MTE2M2I1ODY1MGIxMGYzYWNkZTQ5OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXEqnYVVX5gzrs2nHiKLWHqnzNF_totLfjgXRaDtDUs)

Solucionado el issue con los estilos del carrito
