### ISSUE TITLE
Corregir las imagenes en algunos tamaños de dispositivos

### ISSUE THREAD

**Issue by earias08** [EzequielMassa/AlAnguloFrontend#79]
Proceso
Al ingresar en el detalle de un producto

Resultado esperado
visualizar los datos del producto correctamente

Resultado actual
Las imagenes de productos, en dispositivos como tablets no se visualizan correctamente. Ajustar las imagenes para que se visualicen sin ser deformadas en dispositivos small, medium y large.

Captura
![image](https://github.com/EzequielMassa/AlAnguloFrontend/assets/18445151/a999b239-b7eb-4517-8fb8-6196eda51d4d)
![image](https://github.com/EzequielMassa/AlAnguloFrontend/assets/18445151/f4bfbc07-7b28-4947-afe2-9ab8493392f0)

**Comment by FedericoFrau** [comment]
![AlAnguloImgFix](https://github.com/EzequielMassa/AlAnguloFrontend/assets/136205127/f5532dd1-514b-435b-af85-a395a2e649dc)

-Se solucionó el problema mencionado de proporcionalidad en las imágenes de productos que sucedían en ciertos tamaños de pantalla.
