### ISSUE TITLE
Corregir detalles de página de error 404

### ISSUE THREAD

**Issue by earias08** [EzequielMassa/AlAnguloFrontend#80]
Proceso
Al ingresar a la página de error 404

Resultado esperado
visualizar el estilo de la página de error de la misma manera, en todos los tamaños de dispositivos

Resultado actual
En dispositivos pequeños, el fondo de la web queda un poco mas chico que la altura del viewport. En dispositivos medianos y grandes se visualiza correctamente

Captura
![image](https://github.com/EzequielMassa/AlAnguloFrontend/assets/18445151/0591dbc9-6ff3-42c9-9e59-56259e972e98)

**Comment by facundoit** [comment]
Corregido el problema mencionado en el 404
